### ISSUE TITLE
新增 config 文件夹

### ISSUE THREAD

**Issue by fahchen** [Byzanteam/handbook#12]
- [x] editorconfig

**Comment by fahchen** [comment]
```editorconfig
# EditorConfig is awesome: https://EditorConfig.org

# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true
insert_final_newline = true
trim_trailing_whitespace = true

[.go]
indent_style = tab
indent_size = 4

[*.yml]
indent_style = space
indent_size = 2

[*.js]
indent_style = space
indent_size = 2
```

**Comment by vanppo** [comment]
> ```editorconfig
> # EditorConfig is awesome: https://EditorConfig.org
> 
> # top-most EditorConfig file
> root = true
> 
> # Unix-style newlines with a newline ending every file
> [*]
> end_of_line = lf
> insert_final_newline = true
> insert_final_newline = true
> trim_trailing_whitespace = true
> 
> [.go]
> indent_style = tab
> indent_size = 4
> 
> [*.yml]
> indent_style = space
> indent_size = 2
> 
> [*.js]
> indent_style = space
> indent_size = 2
> ```

```editorconfig
root = true

[*]
charset = utf-8
end_of_line = lf
indent_style = space
indent_size = 2
insert_final_newline = true
trim_trailing_whitespace = true

[*.go]
indent_style = tab

[*.md]
trim_trailing_whitespace = false

[Makefile]
indent_style = tab
```

**Comment by fahchen** [comment]
https://github.com/github/gitignore
