### ISSUE TITLE
note

### ISSUE THREAD

**Issue by fahchen** [Byzanteam/handbook#16]
> Scan for NOTE, OPTIMIZE, TODO, HACK, XXX, FIXME, and BUG comments within your source, and print them to stdout so you can deal with them. This is similar to the rake notes task from Rails.

https://github.com/JohnPostlethwait/fixme

**Comment by fahchen** [comment]
@Leecason 你补一下这个吧

**Comment by Leecason** [comment]
```
TODO: 标识处有功能代码待编写
FIXME: 标识处代码需要修正，甚至代码是错误的，不能工作，需要修复
XXX: 标识处代码虽然实现了功能，但是实现的方法有待商榷，希望将来能改进
OPTIMIZE: 标示处代码可能是低效的，待优化
HACK: 标识处代码需要根据自己的需求去调整程序代码
```

https://github.com/polarmobile/coffeescript-style-guide#annotations
https://github.com/jelera/vim-javascript-syntax/pull/78/files
https://github.com/JohnPostlethwait/fixme

**Comment by fahchen** [comment]
@Leecason 你提个 PR 写到一个 markdown 吧
