### ISSUE TITLE
feat: 版本发布规范

### ISSUE THREAD

**Issue by fahchen** [Byzanteam/handbook#19]
版本构建的规则，如命名规则，构建周期，构建流程等

**Comment by jonyhy96** [comment]
[SemVer](https://semver.org/)

**Comment by fahchen** [comment]
做成 action，方便大家一起用

**Comment by vanppo** [comment]
做成 Action 是什么意思呀？写成配置文件么？

**Comment by fahchen** [comment]
> 做成 Action 是什么意思呀？写成配置文件么？

GitHub action
