### ISSUE TITLE
Git Commit Message Conventions

### ISSUE THREAD

**Issue by fahchen** [Byzanteam/handbook#2]

**Comment by fahchen** [comment]
@ByzantiumTeam/datavisualization @ByzantiumTeam/jet @ByzantiumTeam/slp 各位看看，我们理一下对 commit  message 的一些要求

@usernameisMan 你贴一下相关的链接，和你的想法

**Comment by usernameisMan** [comment]
> @ ByzantiumTeam / datavisualization @ ByzantiumTeam / jet @ ByzantiumTeam / slp各位看看，我们理一下对提交消息的一些要求
> 
> @usernameisMan你贴一下相关的链接，和你的想法

我觉得格式可以不按照下面这个链接，但是可以引入Header type 里面的东西  放在 commit message 最前面
[Git Commit Message Conventions](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#heading=h.fpepsvr2gqby)
[Commit message 和 change log编写规范-阮一峰](http://www.ruanyifeng.com/blog/2016/01/commit_message_change_log.html)
